### ISSUE TITLE
Not compatible with swiftmailer 6

### ISSUE THREAD

**Issue by Soullivaneuh** [snc/SncRedisBundle#359]
During a composer update:

```
Warning: Uncaught ReflectionException: Class Swift_Mime_Message not found in /code/vendor/snc/redis-bundle/SwiftMailer/RedisSpool.php:17
Stack trace:
#0 /code/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php(146): require('/code/vendor/sn...')
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('Snc\\RedisBundle...')
#2 [internal function]: spl_autoload_call('Snc\\RedisBundle...')
#3 /code/vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ClassExistenceResource.php(78): class_exists('Snc\\RedisBundle...')
#4 /code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(361): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
#5 /code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(397): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('Snc\\RedisBundle...', false)
#6 /code/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ in /code/vendor/snc/redis-bundle/SwiftMailer/RedisSpool.php on line 17

Fatal error: Declaration of Snc\RedisBundle\SwiftMailer\RedisSpool::queueMessage(Swift_Mime_Message $message) must be compatible with Swift_Spool::queueMessage(Swift_Mime_SimpleMessage $message) in /code/vendor/snc/redis-bundle/SwiftMailer/RedisSpool.php on line 17
```

At a first time, a `conflict` rules should be added to prevent this issue.

After that, make it compatible in a BC way if possible. :wink: 

I may take a look at this later.

Related: #350

**Comment by snc** [comment]
I've just tagged 2.0.3.
